using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;
using Sentinel.Interfaces;

namespace Sentinel.Services
{
    /// <summary>
    /// Generates test reports with step logs and screenshots.
    /// Outputs Markdown files for easy review.
    /// </summary>
    public class TestReportService : ITestReporter
    {
        private string _testName;
        private DateTime _startTime;
        private List<TestStep> _steps;
        private string _reportDirectory;
        
        public TestReportService(string reportDirectory = "Assets/TestReports")
        {
            _reportDirectory = reportDirectory;
            _steps = new List<TestStep>();
        }
        
        public void StartTest(string testName)
        {
            _testName = testName;
            _startTime = DateTime.Now;
            _steps.Clear();
            
            // Ensure directory exists
            if (!Directory.Exists(_reportDirectory))
            {
                Directory.CreateDirectory(_reportDirectory);
            }
            
            Debug.Log($"[Sentinel] Test started: {testName}");
        }
        
        public void LogStep(string action, string result)
        {
            _steps.Add(new TestStep
            {
                Timestamp = DateTime.Now,
                Action = action,
                Result = result
            });
            
            Debug.Log($"[Sentinel] Step: {action} -> {result}");
        }
        
        public string CaptureScreenshot(string label)
        {
            string timestamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");
            string safeName = SanitizeFilename(label);
            string filename = $"{safeName}_{timestamp}.png";
            string fullPath = Path.Combine(_reportDirectory, filename);
            
            try
            {
                ScreenCapture.CaptureScreenshot(fullPath);
                
                _steps.Add(new TestStep
                {
                    Timestamp = DateTime.Now,
                    Action = $"Screenshot: {label}",
                    Result = filename,
                    IsScreenshot = true
                });
                
                Debug.Log($"[Sentinel] Screenshot saved: {fullPath}");
                return fullPath;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[Sentinel] Screenshot failed: {ex.Message}");
                return null;
            }
        }
        
        public string FinishTest(bool success, string summary)
        {
            DateTime endTime = DateTime.Now;
            TimeSpan duration = endTime - _startTime;
            
            string reportFilename = $"TestReport_{SanitizeFilename(_testName)}_{_startTime:yyyyMMdd_HHmmss}.md";
            string reportPath = Path.Combine(_reportDirectory, reportFilename);
            
            StringBuilder sb = new StringBuilder();
            
            // Header
            sb.AppendLine($"# Test Report: {_testName}");
            sb.AppendLine();
            sb.AppendLine($"**Status**: {(success ? "✅ PASSED" : "❌ FAILED")}");
            sb.AppendLine($"**Start**: {_startTime:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine($"**End**: {endTime:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine($"**Duration**: {duration.TotalSeconds:F2}s");
            sb.AppendLine();
            
            // Summary
            sb.AppendLine("## Summary");
            sb.AppendLine(summary);
            sb.AppendLine();
            
            // Steps
            sb.AppendLine("## Steps");
            sb.AppendLine();
            sb.AppendLine("| # | Time | Action | Result |");
            sb.AppendLine("|---|------|--------|--------|");
            
            for (int i = 0; i < _steps.Count; i++)
            {
                TestStep step = _steps[i];
                string time = step.Timestamp.ToString("HH:mm:ss");
                string result = step.IsScreenshot 
                    ? $"![{step.Action}]({step.Result})" 
                    : step.Result;
                
                sb.AppendLine($"| {i + 1} | {time} | {step.Action} | {result} |");
            }
            
            sb.AppendLine();
            sb.AppendLine("---");
            sb.AppendLine("*Generated by Sentinel Testing Agent*");
            
            try
            {
                File.WriteAllText(reportPath, sb.ToString());
                Debug.Log($"[Sentinel] Report saved: {reportPath}");
                return reportPath;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[Sentinel] Report save failed: {ex.Message}");
                return null;
            }
        }
        
        private string SanitizeFilename(string name)
        {
            if (string.IsNullOrEmpty(name)) return "unnamed";
            
            char[] invalid = Path.GetInvalidFileNameChars();
            StringBuilder sb = new StringBuilder();
            
            foreach (char c in name)
            {
                if (Array.IndexOf(invalid, c) < 0 && c != ' ')
                {
                    sb.Append(c);
                }
                else if (c == ' ')
                {
                    sb.Append('_');
                }
            }
            
            return sb.ToString();
        }
        
        private struct TestStep
        {
            public DateTime Timestamp;
            public string Action;
            public string Result;
            public bool IsScreenshot;
        }
    }
}
